<?php

/**
 * Basecliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $empresa
 * @property string $cuit
 * @property string $direccion
 * @property integer $ciudades_id
 * @property string $telefono
 * @property string $mail
 * @property string $web
 * @property clob $referencias_comerciales
 * @property integer $transportes_id
 * @property integer $tiposactividades_id
 * @property clob $referidos
 * @property integer $usuarios_id
 * @property  $created_at
 * @property  $updated_at
 * @property transporte $transporte
 * @property tiposactividad $tiposactividad
 * @property ciudad $ciudad
 * 
 * @method integer        getId()                      Returns the current record's "id" value
 * @method string         getEmpresa()                 Returns the current record's "empresa" value
 * @method string         getCuit()                    Returns the current record's "cuit" value
 * @method string         getDireccion()               Returns the current record's "direccion" value
 * @method integer        getCiudadesId()              Returns the current record's "ciudades_id" value
 * @method string         getTelefono()                Returns the current record's "telefono" value
 * @method string         getMail()                    Returns the current record's "mail" value
 * @method string         getWeb()                     Returns the current record's "web" value
 * @method clob           getReferenciasComerciales()  Returns the current record's "referencias_comerciales" value
 * @method integer        getTransportesId()           Returns the current record's "transportes_id" value
 * @method integer        getTiposactividadesId()      Returns the current record's "tiposactividades_id" value
 * @method clob           getReferidos()               Returns the current record's "referidos" value
 * @method integer        getUsuariosId()              Returns the current record's "usuarios_id" value
 * @method transporte     getTransporte()              Returns the current record's "transporte" value
 * @method tiposactividad getTiposactividad()          Returns the current record's "tiposactividad" value
 * @method ciudad         getCiudad()                  Returns the current record's "ciudad" value
 * @method cliente        setId()                      Sets the current record's "id" value
 * @method cliente        setEmpresa()                 Sets the current record's "empresa" value
 * @method cliente        setCuit()                    Sets the current record's "cuit" value
 * @method cliente        setDireccion()               Sets the current record's "direccion" value
 * @method cliente        setCiudadesId()              Sets the current record's "ciudades_id" value
 * @method cliente        setTelefono()                Sets the current record's "telefono" value
 * @method cliente        setMail()                    Sets the current record's "mail" value
 * @method cliente        setWeb()                     Sets the current record's "web" value
 * @method cliente        setReferenciasComerciales()  Sets the current record's "referencias_comerciales" value
 * @method cliente        setTransportesId()           Sets the current record's "transportes_id" value
 * @method cliente        setTiposactividadesId()      Sets the current record's "tiposactividades_id" value
 * @method cliente        setReferidos()               Sets the current record's "referidos" value
 * @method cliente        setUsuariosId()              Sets the current record's "usuarios_id" value
 * @method cliente        setTransporte()              Sets the current record's "transporte" value
 * @method cliente        setTiposactividad()          Sets the current record's "tiposactividad" value
 * @method cliente        setCiudad()                  Sets the current record's "ciudad" value
 * 
 * @package    importmol
 * @subpackage model
 * @author     Javier Marcon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basecliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('clientes');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 20,
             ));
        $this->hasColumn('empresa', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 100,
             ));
        $this->hasColumn('cuit', 'string', 13, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 13,
             ));
        $this->hasColumn('direccion', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('ciudades_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('telefono', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'length' => 100,
             ));
        $this->hasColumn('mail', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('web', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'default' => '',
             'length' => 100,
             ));
        $this->hasColumn('referencias_comerciales', 'clob', 65535, array(
             'type' => 'clob',
             'notnull' => false,
             'length' => 65535,
             ));
        $this->hasColumn('transportes_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('tiposactividades_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('referidos', 'clob', 65535, array(
             'type' => 'clob',
             'notnull' => false,
             'length' => 65535,
             ));
        $this->hasColumn('usuarios_id', 'integer', 20, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('created_at', '', null);
        $this->hasColumn('updated_at', '', null);


        $this->index('fk_clientes_transportes', array(
             'fields' => 
             array(
              0 => 'transportes_id',
             ),
             ));
        $this->index('fk_clientes_tiposactividades1', array(
             'fields' => 
             array(
              0 => 'tiposactividades_id',
             ),
             ));
        $this->index('fk_clientes_ciudades1', array(
             'fields' => 
             array(
              0 => 'ciudades_id',
             ),
             ));
        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('transporte', array(
             'local' => 'transportes_id',
             'foreign' => 'id'));

        $this->hasOne('tiposactividad', array(
             'local' => 'tiposactividades_id',
             'foreign' => 'id'));

        $this->hasOne('ciudad', array(
             'local' => 'ciudades_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}