<?php

/**
 * Basepais
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $codigo
 * @property string $nombre
 * @property string $continente
 * @property string $region
 * @property string $nombrelocal
 * @property integer $capital
 * @property string $codigo2
 * @property Doctrine_Collection $paises
 * 
 * @method string              getCodigo()      Returns the current record's "codigo" value
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method string              getContinente()  Returns the current record's "continente" value
 * @method string              getRegion()      Returns the current record's "region" value
 * @method string              getNombrelocal() Returns the current record's "nombrelocal" value
 * @method integer             getCapital()     Returns the current record's "capital" value
 * @method string              getCodigo2()     Returns the current record's "codigo2" value
 * @method Doctrine_Collection getPaises()      Returns the current record's "paises" collection
 * @method pais                setCodigo()      Sets the current record's "codigo" value
 * @method pais                setNombre()      Sets the current record's "nombre" value
 * @method pais                setContinente()  Sets the current record's "continente" value
 * @method pais                setRegion()      Sets the current record's "region" value
 * @method pais                setNombrelocal() Sets the current record's "nombrelocal" value
 * @method pais                setCapital()     Sets the current record's "capital" value
 * @method pais                setCodigo2()     Sets the current record's "codigo2" value
 * @method pais                setPaises()      Sets the current record's "paises" collection
 * 
 * @package    importmol
 * @subpackage model
 * @author     Javier Marcon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basepais extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('paises');
        $this->hasColumn('codigo', 'string', 3, array(
             'type' => 'string',
             'primary' => true,
             'fixed' => 1,
             'length' => 3,
             ));
        $this->hasColumn('nombre', 'string', 52, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'fixed' => 1,
             'length' => 52,
             ));
        $this->hasColumn('continente', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'default' => 'Asia',
             'length' => 15,
             ));
        $this->hasColumn('region', 'string', 26, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'fixed' => 1,
             'length' => 26,
             ));
        $this->hasColumn('nombrelocal', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'fixed' => 1,
             'length' => 45,
             ));
        $this->hasColumn('capital', 'integer', 20, array(
             'type' => 'integer',
             'length' => 20,
             ));
        $this->hasColumn('codigo2', 'string', 2, array(
             'type' => 'string',
             'notnull' => true,
             'default' => '',
             'fixed' => 1,
             'length' => 2,
             ));

        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ciudad as paises', array(
             'local' => 'codigo',
             'foreign' => 'paises_codigo'));
    }
}