<?php

/**
 * Basetiposactividad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nombre
 * @property Doctrine_Collection $clientes
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getNombre()   Returns the current record's "nombre" value
 * @method Doctrine_Collection getClientes() Returns the current record's "clientes" collection
 * @method tiposactividad      setId()       Sets the current record's "id" value
 * @method tiposactividad      setNombre()   Sets the current record's "nombre" value
 * @method tiposactividad      setClientes() Sets the current record's "clientes" collection
 * 
 * @package    importmol
 * @subpackage model
 * @author     Javier Marcon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Basetiposactividad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tiposactividades');
        $this->hasColumn('id', 'integer', 20, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'length' => 20,
             ));
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));

        $this->option('collate', 'latin1_swedish_ci');
        $this->option('charset', 'latin1');
        $this->option('type', 'InnoDB');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sf_guard_user_profile as clientes', array(
             'local' => 'id',
             'foreign' => 'tiposactividades_id'));
    }
}