<?php

/**
 * ProductImageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductImageTable extends PluginProductImageTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProductImageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ProductImage');
    }
}