<?php

/**
 * categoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    importmol
 * @subpackage model
 * @author     Javier Marcon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class categoria extends Basecategoria
{
    public function __toString()
    {
		return $this->getNombre();
    }

	public function getConProductosSql()
		{
		$q = Doctrine_Query::create()
	    ->from('producto p')
	    ->where('p.categorias_id = ?', $this->getId()) ;
		
		return Doctrine_Core::getTable('producto')->getConProductosSql($q);
		}

    public function getConProductos($max = 10)
    {
	
	    $q = $this->getConProductosSql()
		//->addOrderBy('root_id asc')
	    //->addOrderBy('lft asc');
	    ->limit($max);
	//$q = $this->createQuery('c')
	//    ->leftJoin('c.productos p')
	//    ->where('p.id = ?', $this->getId())
	//    ->limit($max);

	return $q->execute();
	
    }
    
    public function contarProductos()
    {
	//$q = Doctrine_Query::create()
	//    ->from('producto p')
	//    ->where('p.id = ?', $this->getId());

	//return Doctrine_Core::getTable('producto')->contarProductos($q);
	return $this->getConProductosSql()->count();
    }
}
