<?php

/**
 * categoriaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class categoriaTable extends Doctrine_Table
{
    
  
    /**
     * Returns an instance of this class.
     *
     * @return object categoriaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('categoria');
    }

    public function getCategoriaSql()
    {
	$q = Doctrine_Query::create()
	    ->from('categoria c')
	    ->addOrderBy('c.root_id asc')
	    ->addOrderBy('c.lft asc');
	
	return $q;
    }
    
    public function getDeProductos()
    {
	$q = $this->getCategoriaSql()
	    ->leftJoin('c.productos p');

	return $q->execute();

    }

    public function getListaCategorias()
    {
	return $this->getCategoriaSql()->execute();
    
	
  
    }

    
}