<?php

/**
 * ciudadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ciudadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ciudadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ciudad');
    }
}