<?php

/**
 * clienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class clienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object clienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('cliente');
    }
}