<?php

/**
 * paisTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class paisTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object paisTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('pais');
    }
}