<?php

/**
 * sf_guard_user_profileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sf_guard_user_profileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object sf_guard_user_profileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sf_guard_user_profile');
    }
}