<?php

/**
 * tiposactividadTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class tiposactividadTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object tiposactividadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('tiposactividad');
    }
}