<?php

/**
 * transporteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class transporteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object transporteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('transporte');
    }
}