<?php

/**
 * BaseProductColor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $product_id
 * @property string $color
 * @property Product $Product
 * 
 * @method integer      getProductId()  Returns the current record's "product_id" value
 * @method string       getColor()      Returns the current record's "color" value
 * @method Product      getProduct()    Returns the current record's "Product" value
 * @method ProductColor setProductId()  Sets the current record's "product_id" value
 * @method ProductColor setColor()      Sets the current record's "color" value
 * @method ProductColor setProduct()    Sets the current record's "Product" value
 * 
 * @package    importmol
 * @subpackage model
 * @author     Javier Marcon
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProductColor extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product_color');
        $this->hasColumn('product_id', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 4,
             ));
        $this->hasColumn('color', 'string', 6, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 6,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Product', array(
             'local' => 'product_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}