generator:
  class: sfDoctrineGenerator
  param:
    model_class:           producto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          producto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:         Productos
        layout:        stacked
        display:       [=nombre, descripcion, foto1, foto2, foto3, foto4, foto5, foto6, categoria]
        params:  |
          %%nombre%% <small>%%descripcion%%</small> 
          <img src="/uploads/productos/s_%%foto1%%" alt="" />
          <img src="/uploads/productos/s_%%foto2%%" alt="" />
          <img src="/uploads/productos/s_%%foto3%%" alt="" />
          <img src="/uploads/productos/s_%%foto4%%" alt="" />
          <img src="/uploads/productos/s_%%foto5%%" alt="" />
          <img src="/uploads/productos/s_%%foto6%%" alt="" />
          (<strong>%%categoria%%</strong>)
        #max_per_page:  10
        #sort:          [expires_at, desc]

      filter:  ~
      form:    ~
      edit:
        title: Editando el producto %%nombre%%
      new:
        title: Nuevo Producto
