<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addproductcolor extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('product_color', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'notnull' => true,
              'length' => 4,
             ),
             'color' => 
             array(
              'type' => 'string',
              'notnull' => true,
              'length' => 6,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('product_color');
    }
}