<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addproductimage extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('product_image', array(
             'id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'autoincrement' => true,
              'length' => 4,
             ),
             'product_id' => 
             array(
              'type' => 'integer',
              'length' => 4,
             ),
             'position' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'image_name' => 
             array(
              'type' => 'string',
              'length' => 255,
             ),
             'image_name_x1' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'image_name_y1' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'image_name_x2' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             'image_name_y2' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
              'product_image_position_sortable' => 
              array(
              'fields' => 
              array(
               0 => 'position',
               1 => 'product_id',
              ),
              'type' => 'unique',
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('product_image');
    }
}